### PR TITLE
Completed Login Index Page

### PR DESCRIPTION
**Pull request by kanukantia**
@ravi2krishna Please review code.

### CODE REVIEW

**Review by ravi2krishna — CHANGES_REQUESTED** [review]
@kanukantia Image size is quite big set the image width to 20%

**Comment by kanukantia** [comment]
@ravi2krishna Image width set as per request 20px

**Review by kanukantia — COMMENTED** [review]
Good Job

**Review by ravi2krishna — APPROVED** [review]
@kanukantia Good Job

**Pull request merged**
